### ISSUE TITLE
Broken link to download deployment zip

### ISSUE THREAD

**Issue by ignaciofls** [Azure/AIPlatform#1]
I get a 404 when trying to download the zip under this section:
_"Step 1 - Download the required code to you computer
The deployment runs locally in your computer. You have 2 alternative methods to do it:

Download and extract the file deployment package.zip located here"_ (here points to https://github.com/Azure/AIPlatform/tree/master/CognitiveSearch/Deployment)

I guess it should point to:
https://github.com/Azure/AIPlatform/blob/master/end-to-end-solutions/kma/Deployment/KMA.zip

**Comment by Rodrigossz** [comment]
Fixed. Tks!
