### ISSUE TITLE
Entity Recognition

### ISSUE THREAD

**Issue by usistan** [Azure/AIPlatform#10]
Is it possible to restrict the entities displayed in the facets?
Especially with bi-lingual documents we saw that a lot of garbage entities are recognized. If there was something like a confidence score or a frequency count threshold for each entity it would improve the first impression of the solution.

**Comment by Rodrigossz** [comment]
It has filters and you can make them go away. Confidence is returned but we are not considering. You can change the skillset, the indexer, the index, and the interface. If you do it, let us know, we can update the solution with your code.
