### ISSUE TITLE
Deploy.ps1 script seems to ignore the '-location' argument

### ISSUE THREAD

**Issue by aldelar** [Azure/AIPlatform#6]
2 failing test scenarios:
- run Deploy.ps1 with '-location westus2' as a parameter, the resources are deployed in 'centralus'
- modify the Deploy.ps1 script itself to replace the default to "centralus" with '[string]$location = "westus2", then run the script again, the resource group is in westus2, but the resources within are still created in centralus

**Comment by Rodrigossz** [comment]
Fixed with detailed instructions. Tks

**Comment by aldelar** [comment]
I ran an install again with the latest code pull, with -location westus2, and only the resource group gets created in westus2, all other resources are still in centralus.
