### ISSUE TITLE
Main Search Web UI Page doesn't handle pagination properly (creating performance issues)

### ISSUE THREAD

**Issue by aldelar** [Azure/AIPlatform#7]
Scenario:
- load about 2000 documents into the supporting Storage Account for indexing
- once indexed, go to the Web UI of the solution
- EXPECTED:
  page comes up very fast (modern UI experience, 100 ms territory)
  page only displays 10 results as per expected pagination
- OBSERVED:
  page comes back very slowly (48 seconds observed with my sample data)
  page displays ALL documents (did not account but a LOT of docs) with pagination indicating:
     // Page: 1 [showing documents 1 to 10]  (NOTE: only '1' page is available, there should be 200+)
     // Available Results: 2377

**The broken pagination makes this application unusable.**

**Comment by Rodrigossz** [comment]
Fixed. Tks
