### ISSUE TITLE
Location flag has no effect

### ISSUE THREAD

**Issue by usistan** [Azure/AIPlatform#8]
- The location seems to be hard coded to 'centralus' and the location flag does not take precedence (we needed to deploy in westeurope). 
- we also changed to the Blobstore to the StorageV2 kind so that we can continue to upload docs directly in blobstore
https://github.com/usistan/hawkeye/tree/master/Deployment

**Comment by Rodrigossz** [comment]
This is not an issue. And location is explained in the deployment page.
